- routers/user_router.py
- schemas/user_schema.py
- tests/user_test.py
Make the code more readable and maintanable
Refactor to use optional for optional fields. 
- pytest
> Refactor to use optional

- schemas/announcement_schema.py
- services/announcement_service.py
Refactor to remove deprecated methods
- pytest
> Refactor and remove deprecated methods

- repository/user_repository.py
- routers/user_router.py
- services/user_service.py
- tests/user_test.py
closes https://github.com/PkFokam-Alumni-Network/CommunityBackendService/issues/33
created route to fetch all users 
Pytest
<!![Screenshot 2024-12-16 210637](https://github.com/user-attachments/assets/7b1e29df-fcf0-4221-b901-49633abf6904)
> created route for fetching all users

- main.py
- services/user_service.py
- utils/func_utils.py
> Add CORS to test on Frontend

- .gitignore
- models/announcement.py
- models/user.py
- routers/user_router.py
- schemas/user_schema.py
- services/user_service.py
- utils/func_utils.py
- To match the frontend model
- Passed user detail in the login api
- Removed deprecated methods
- Deleted s3 uploading (will use later)
- pytests
> Upgrade the model and pass user info in the login endpoint

- database.py
- docker-compose.yaml
- Change docker compose to add a volume for persistent storage across deployments
- Use sqlite db in prod and a temp db locally
> Change docker-compose to add volumes

- main.py
- services/user_service.py
> Fix validation of null for mentors

- routers/user_router.py
- schemas/user_schema.py
- tests/user_test.py
> Expose new fields at creation

- routers/user_router.py
> Add a method to upload picture

- repository/user_repository.py
- schemas/user_schema.py
> Expose user role

- routers/user_router.py
- services/user_service.py
- utils/func_utils.py
- utils/image_utils.py
- The frontend was not able to display images appropriately because the s3 path was incorrect to access the image
> Fix s3 paths for displaying on frontend

- auth.py
- docs.py
- main.py
- routers/user_router.py
- Block access to user docs behind an HTML form
> Secure the docs

- main.py
- models/__init__.py
- models/event.py
- models/user.py
- models/user_event.py
- repository/event_repository.py
- repository/user_event_repository.py
- routers/event_router.py
- schemas/event_schema.py
- services/event_service.py
- tests/announcement_test.py
- tests/conftest.py
- tests/event_test.py
- tests/user_test.py
- utils/init_db.py
- Closes https://github.com/PkFokam-Alumni-Network/CommunityBackendService/issues/25
- Added a new model for Event
- Added an association table for Events and Users
- Added the relationship inside User, Event models
- Added repositories
- Added services
- Added routers
- pytest
- Postman (too many screenshots to take but Unit tests cover all the cases of the new methods)
> Add support for events

- models/event.py
- routers/event_router.py
- schemas/event_schema.py
- services/event_service.py
> Add image field

- repository/user_repository.py
- routers/user_router.py
- schemas/user_schema.py
- services/user_service.py
> Fetch users by ID

- routers/event_router.py
- schemas/event_schema.py
- schemas/user_schema.py
- services/event_service.py
> Expose attendees

- utils/image_utils.py
> Change profile picture

- utils/image_utils.py
> Add support for mpo files

- routers/user_router.py
- services/user_service.py
- tests/user_test.py
> Add counts

- repository/user_repository.py
- routers/user_router.py
- services/user_service.py
- tests/user_test.py
- We have had troubles with using emails when users wanted to update their email, password and other things in the UI. A better way was to use the id. 
- pytest
> Refactor to use id instead of email

- services/user_service.py
- templates/password_reset.html
- utils/func_utils.py
Refactored the change password email for better user experience
Added an email template in HTML and changed the email format for resetting password
Postman
> changed email format and added an HTML template

- routers/user_router.py
- tests/user_test.py
Hide PII from designer as she investigates a way to enhance our repo
> Hide stuff from designer

- repository/user_event_repository.py
- routers/event_router.py
- services/event_service.py
- tests/event_test.py
> Migrate to use user_id in user_events

- routers/announcement_router.py
- routers/event_router.py
- routers/user_router.py
- tests/event_test.py
> Fix our observability in router request

- routers/announcement_router.py
- routers/event_router.py
- routers/user_router.py
> Reduce log verbosity

- routers/event_router.py
- Closes https://github.com/PkFokam-Alumni-Network/CommunityBackendService/issues/139
- Removed `/users/{user_email}/events` endpoint from event router
- Added optional `user_email` query parameter to `/events/` endpoint
- Added imports for `Query` and `Optional` from FastAPI
> replace user events endpoint with query parameter filtering
